#pragma kernel SimulateParticles
#pragma kernel RenderSimulation

RWTexture2D<float4> Result;

float4 BGColor;
int WIDTH;
int HEIGHT;
 
struct Planet
{
    float2 position;
    float radius;
    float mass;
};
RWStructuredBuffer<Planet> Planets;
int NumPlanets;

struct Particle
{
    float2 position;
    float2 velocity;
};
RWStructuredBuffer<Particle> Particles;
int NumParticles;

float2 GravityOnParticle(float2 pos)
{
    const float G = 5; // Arbitrary "Universal gravity constant" 
    float2 velocity = float2(0.0, 0.0); 
    for(int i = 0; i < NumPlanets; i++)
    {
        Planet body = Planets[i];
        float r = distance(pos, body.position);
        float force = G*body.mass*1.0/pow(r, 2);
        velocity += force*normalize(body.position - pos);
    }
    return velocity;
}

float2 CollideWithBodies(Particle p)
{
    for(int i = 0; i < NumPlanets; i++)
    {
        Planet body = Planets[i];
        if(distance(p.position, body.position) < body.radius)
        {
            float2 normal = normalize(p.position - body.position);
            return 0.75*(p.velocity- 2*dot(normal, p.velocity)*normal);
        }
    }
    return p.velocity;
}

[numthreads(4,1,1)] 
void SimulateParticles (uint3 id : SV_DispatchThreadID)
{
    if(id.x == 0) return;
    Particle p = Particles[id.x];

    Particles[id.x].velocity += GravityOnParticle(p.position);
    Particles[id.x].velocity = CollideWithBodies(Particles[id.x]);

    Particles[id.x].position += Particles[id.x].velocity;
}

// float4 RenderScene(uint2 pos)
// {
//     for(int i = 0; i < NumPlanets; i++)
//     {
//         if(distance(pos, Planets[i].position) < Planets[i].radius)
//         {
//             return float4(1.0, 0.0, 0.0, 1.0);
//         } 
//     }
//     for(int j = 1; j < NumParticles; j++)
//     {
//         if(distance(pos, Particles[j].position) < 1 && NumParticles != 1 /*Zero length buffer guard*/)
//         {
//             return float4(1.0, 1.0, 1.0,1.0);
//         }
//     }

//     return BGColor;
// }

[numthreads(8,8,1)] 
void RenderSimulation (uint3 id : SV_DispatchThreadID)
{
    Result[id.xy] = RenderScene(id.xy);
}