#pragma kernel SimulateParticles
#pragma kernel RenderBackground
#pragma kernel RenderParticles

int WIDTH;
int HEIGHT;
 
struct Planet
{
    float2 position;
    float radius;
    float mass;
    float4 color;
};

RWStructuredBuffer<Planet> Planets;
int NumPlanets;

struct Particle
{
    float2 position;
    float2 velocity;
    float radius;
};

RWStructuredBuffer<Particle> Particles;
int NumParticles;

float2 GravityOnParticle(float2 pos)
{
    const float G = 5; // Arbitrary "Universal gravity constant" 
    float2 velocity = float2(0.0, 0.0); 
    for(int i = 0; i < NumPlanets; i++)
    {
        Planet body = Planets[i];
        float r = distance(pos, body.position);
        float force = G*body.mass*1.0/pow(r, 2);
        velocity += force*normalize(body.position - pos);
    }
    return velocity;
}

void CollideWithBodies(inout Particle p)
{
    const float frictionCoefficient = 0.85;
    const float restitutionCoefficient = 0.85;
    for(int i = 0; i < NumPlanets; i++)
    {
        Planet body = Planets[i];
        if(distance(p.position, body.position) < body.radius + p.radius)
        {
            float2 normal = normalize(p.position - body.position);
            p.position = body.position + normal*(body.radius + p.radius);

            float vAlongNormal = dot(normal, p.velocity);
            if(vAlongNormal < 0)
            {
                p.velocity = frictionCoefficient*(p.velocity- (1 + restitutionCoefficient)*vAlongNormal*normal);
            }
        }
    }
}

[numthreads(128,1,1)] 
void SimulateParticles (uint3 id : SV_DispatchThreadID)
{
    if(id.x == 0) return;
    Particle p = Particles[id.x];

    Particles[id.x].velocity += GravityOnParticle(p.position);
    Particles[id.x].position += Particles[id.x].velocity;
    CollideWithBodies(Particles[id.x]);
}

RWTexture2D<float4> Result;
float4 BGColor;

[numthreads(8,8,1)] 
void RenderBackground (uint3 id : SV_DispatchThreadID)
{
    float4 color = BGColor;
    for(int i = 0; i < NumPlanets; i++)
    {
        if(distance(id.xy, Planets[i].position) < Planets[i].radius)
        {
            color = Planets[i].color;
        } 
    }
    Result[id.xy] = color;
}

RWStructuredBuffer<float4> ParticleColorGradient;
int NumParticleColors;

float4 SampleColorGradient(float time, int length, RWStructuredBuffer<float4> colors)
{
    float localSample = time*(length-1);
    return lerp(colors[floor(localSample)], colors[ceil(localSample)], frac(localSample));
}

[numthreads(128,1,1)] 
void RenderParticles (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= NumParticles || id.x == 0) return;

    uint2 center = uint2(Particles[id.x].position);
    if(center.x < 0 || center.y < 0 || center.x > WIDTH || center.y > HEIGHT) return;

    const float rad = Particles[id.x].radius; 

    for(int x = center.x - ceil(rad); x <= center.x + ceil(rad); x++)
    {
        for(int y = center.y - ceil(rad); y <= center.y + ceil(rad); y++)
        {
            if(distance(Particles[id.x].position, uint2(x, y)) < rad)
            {
                Result[uint2(x, y)] = SampleColorGradient(clamp(length(Particles[id.x].velocity/2.0), 0, 1) ,NumParticleColors, ParticleColorGradient);
            }
        }
    }
}
