#pragma kernel SimulateParticles
#pragma kernel RenderBackground
#pragma kernel RenderParticles

RWTexture2D<float4> Result;

float4 BGColor;
int WIDTH;
int HEIGHT;
 
struct Planet
{
    float2 position;
    float radius;
    float mass;
};
RWStructuredBuffer<Planet> Planets;
int NumPlanets;

struct Particle
{
    float2 position;
    float2 velocity;
};
RWStructuredBuffer<Particle> Particles;
int NumParticles;

float2 GravityOnParticle(float2 pos)
{
    const float G = 5; // Arbitrary "Universal gravity constant" 
    float2 velocity = float2(0.0, 0.0); 
    for(int i = 0; i < NumPlanets; i++)
    {
        Planet body = Planets[i];
        float r = distance(pos, body.position);
        float force = G*body.mass*1.0/pow(r, 2);
        velocity += force*normalize(body.position - pos);
    }
    return velocity;
}

void CollideWithBodies(inout Particle p)
{
    const float frictionCoefficient = 0.85;
    const float restitutionCoefficient = 0.85;
    for(int i = 0; i < NumPlanets; i++)
    {
        Planet body = Planets[i];
        if(distance(p.position, body.position) < body.radius + 1)
        {
            float2 normal = normalize(p.position - body.position);
            p.position = body.position + normal*(body.radius + 1);

            float vAlongNormal = dot(normal, p.velocity);
            if(vAlongNormal < 0)
            {
                p.velocity = frictionCoefficient*(p.velocity- (1 + restitutionCoefficient)*vAlongNormal*normal);
            }
        }
    }
}

[numthreads(4,1,1)] 
void SimulateParticles (uint3 id : SV_DispatchThreadID)
{
    if(id.x == 0) return;
    Particle p = Particles[id.x];

    Particles[id.x].velocity += GravityOnParticle(p.position);
    Particles[id.x].position += Particles[id.x].velocity;
    CollideWithBodies(Particles[id.x]);
}

[numthreads(8,8,1)] 
void RenderBackground (uint3 id : SV_DispatchThreadID)
{
    float4 color = BGColor;
    for(int i = 0; i < NumPlanets; i++)
    {
        if(distance(id.xy, Planets[i].position) < Planets[i].radius)
        {
            color = float4(1.0, 0.0, 0.0, 1.0);
        } 
    }
    Result[id.xy] = color;
}

[numthreads(64,1,1)] 
void RenderParticles (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= NumParticles || id.x == 0) return;

    uint2 center = uint2(Particles[id.x].position);
    const float rad = 1; 

    for(int x = center.x - ceil(rad); x <= center.x + ceil(rad); x++)
    {
        for(int y = center.y - ceil(rad); y <= center.y + ceil(rad); y++)
        {
            if(distance(Particles[id.x].position, uint2(x, y)) < rad)
            {
                Result[uint2(x, y)] = float4(1.0, 1.0, 1.0,1.0);
            }
        }
    }
}
